src/routers/PlacesAutocompleteRouter.js

The example code for the `lru-cache` had a `dispose` function that's called every time a key is removed, but it was causing an error because the key had no `close` function. 
Verified that this was the error by setting cache size to 1 and `max-age` to 5 seconds, made sure that it repro-ed with these changes, and verified that it does not repro after removing this line.

Removed dispose function from lru-cache constructor

---

README.md
src/Api.js
src/routers/MultiRouteRouter.js

Query strings will have additional `end` and `destinationName` parameters that must be in order. #56 
ex. `&end=coords0&end=coords1&end=coords2&destinationName=name0&destinationName=name1&destinationName=name2`.

Add multiroute endpoint

---

src/utils/AlertsUtils.js
src/utils/GTFSUtils.js
src/utils/LogUtils.js
src/utils/TokenUtils.js

There only needs to be one call to `dotenv.config()`, and it's done in `server.js`. All of the others are redundant. I verified that this doesn't break anything.

Remove unnecessary dotenv calls

---

src/server.js

In the picture below, we can see that the server never fully initialized while availtec was down (between 9AM-12PM)
I added a `Promise.race` to ensure that no matter what happens, the server will advance to the next step after 20 seconds.

Add timeout on server init to bypass availtec being down

---

env.template
src/routers/AlertsRouter.js
src/routers/AllStopsRouter.js
src/server.js
src/utils/AlertsUtils.js
src/utils/AllStopUtils.js
src/utils/EnvUtils.js
src/utils/RealtimeFeedUtils.js
src/utils/TokenUtils.js

Issue #145 
- Replaced old code of fetching stops & alerts with new code to fetch both from the `transit-microservice`
`NOTE`: Not sure if somethings wrong w/ my linter? It seems to have added/removed some spaces in certain lines. Is my linter correct?
Screenshots of responses for `alerts` & `allStops`:
Alerts:
All Stops:

Deprecate fetch of stops & alerts #145

---

.travis.yml
docker_push

- Builds and pushes an image to `transit-node` if push happens on the release branch
- Builds and pushes an image to `transit-dev` if push happens on master branch (unless we want to use a dev branch)
Tested by building a dev image on this branch. Output can be seen here (under "Deploying Application"): https://travis-ci.com/cuappdev/ithaca-transit-backend/jobs/178874188#L509

Travis configuration for master, release

---

.travis.yml

As the title says, the original syntax only recognized the first branch stated.
Just tested on this branch!

Fix travis deploy script to support multiple branches

---

src/routers/v1/RouteRouter.js
src/utils/GraphhopperUtils.js
src/utils/RouteUtils.js
src/utils/RouteV2Utils.js

Right now if ghopper fails to return any bus routes, we just throw an error. This makes the response something like this (https://transit-dev.cornellappdev.com/api/v1/route?arriveBy=0&destinationName=Current%20Location&end=42.43865970526117%2C-76.4841959719327&originName=Asbury%20%40%20Warren&start=42.524723%2C-76.472847&time=1552706100&uid=BFDA3D0E-1E38-4A66-ABBF-DAF1243B246B).
Instead of throwing an error, we should just log the error instead and continue to see if there are any walking routes.

Handle ghopper errors properly

---

src/appdev/ApplicationRouter.js
src/utils/ParseRouteUtils.js
src/utils/RouteUtils.js

First of a few changes addressing #195.
List of changes made:
- Split shared code from `createSectionedRoute` and `getRoutes` into a helper function.
- There's an invariant that a `walkingRoute` will always be returned, I changed our code to anticipate that.
- `adjustRouteTimesIfNecessary` was being used in `RouteUtils`, this should be private to `ParseRouteUtils` to make the logic cleaner.
Screenshot verifying it works on devserver:

Refactor RouteUtils

---

.dockerignore
src/utils/ParseRouteUtils.js

It's fixed:
Verifying that 6:54 doesn't show the 6:53 bus:
I also added `.git` to `.dockerignore` because we don't need it in the build!

Fix bug where buses leaving at current minute did not display

---

src/utils/ParseRouteUtils.js
src/utils/RouteUtils.js

Some quality of life changes for #195, more complicated refactoring will come soon:
- Changed `adjustRouteTimesIfNecessary` to return an `Object`
- Changed `condenseRoute` params to not have defaults, since the single callee provides parameters
- Added helpers to reduce LOC in `parseWalkingRoute` and `parseBusRoutes`
- Added documentation and types to functions that were missing
- Alphabetized imports at top
Verified that all changes work on devserver.

Beginning refactoring of ParseRouteUtils

---

docker-compose/map/Dockerfile
docker-compose/map/config.yml

More progress on #178
The graphhopper map image that I worked on for `0.11` wasn't working, I finally got around to fixing the issue –– this upgrades the graphhopper version from `0.9` to `0.11`!
This also lets use the `graph-cache`, so we can pre-build our images.

Update and fix graphhopper map image

---

.travis.yml

I confirmed that if I change the command to `if [[ "$TRAVIS_PULL_REQUEST" != "false" && "$TRAVIS_PULL_REQUEST_BRANCH" == "kevin/travis" && "$TRAVIS_BRANCH" == "master" ]];` the build would fail
i'm not sure if this is right tho so pls double check

Add check to prevent PR from release to master

---

docker-compose/ghopper-walking/Dockerfile
docker-compose/ghopper-walking/config.yml

This change is deployed in production, it saves us 0.4GB in RAM, and also updates the graphhopper-walking minor version from `0.10` to `0.12`. Addresses #178 and #180 as well!
The last one is the main `graphhopper` image, but I've been having issues with configuring the GTFS file –– I might make an issue in the `graphhopper` repository if I can't figure it out in the next few days.

Update graphhopper-walking minor version to 0.12

---

docker-compose/ghopper-walking/Dockerfile

Realized that when I updated the version, TCAT data was included in the graphhopper walking which isn't necessary.

Remove fetch of TCAT data from ghopper-walking image

---

src/utils/GraphhopperUtils.js

- Adds missing `delayBufferMinutes` argument when logging
Right now when we fail, the response we get is the following b/c we are missing an argument to `getGraphhopperBusParams`:
After the fix, we get the appropriate response (the walking route):

Fix response when we fail to get bus routes

---

src/swagger.json

Update docs to include all of Bus Location's parameters

---

docker-compose.yml
src/utils/RouteUtils.js

Right now we don't do any sort of sorting for routes which leads to this issue sometimes where the first route is objectively worse than the second route.
Fixed:

Add sorting for bus routes

---

docker-compose.yml
src/routers/v1/SearchRouter.js

Update /search endpoint to return lat and long in addition to placeID for googlePlace

---

src/API.js
src/routers/index.js
src/routers/v1/PlaceIDCoordinatesRouter.js
src/routers/v1/PlaceIDCoordsRouter.js
src/routers/v1/SearchRouter.js
src/utils/SearchUtils.js

This PR extracts the placeID to coordinate lookup from `SearchRouter` into its own `PlaceIDCoordsRouter` b/c on iOS we are currently making requests to GooglePlaces SDK for this lookup.
Tests:

Adds PlaceIDCoordsRouter for coord lookup

---

docker-compose/ghopper/Dockerfile
src/utils/GraphhopperUtils.js
src/utils/ParseRouteUtils.js
src/utils/RouteUtils.js

- Update Dockerfile to use Graphhopper 0.11 (even though 0.11 is currently deployed)
- Sometimes the Graphhopper (0.11) bus service will return walking directions in addition to bus directions (if the distance is close enough)
- If the bus service doesn't return walking directions, then we can make a separate request to the Grasshopper walking service to get directions.
- This is good cause we don't have to make extra requests to the walking service if it's not necessary
- Also fixes bug where we get 3 walking directions by filtering walking directions from the buffered requests
Currently deployed and tested on the dev server with the beta app

Utilize Graphhopper 0.11 for walking directions

---

.gitignore
docker-compose.yml

Previously my env files were `.env` and so I didn't realize that building node would still have an issue -- so I caught that today and also updated the gitignore.
#249

Update docker-compose.yml and gitignore

---

src/appdev/ApplicationAPI.js

#177 I've addressed the last traditional for loop that could be replaced with a forEach
Sorry for the duplicate PR but I'll be breaking up my first PR into chunks because the massive change is breaking the dev server and I don't know why, so I'm testing each chunk. I've tested this change on the dev server (transit-dev:alanna1047), and I know for sure that it works.
Once I get all my other PRs in, I'll delete my old one.
When doing a search in VSCode, there are two more traditional `for` loops left because the first one we modify the array based on the index (so it didn't make sense to me to change that to a `forEach`) and the second one we're not looping through an array at all:

Replace last remove-able for loop with forEach

---

src/routers/v1/RouteRouter.js

Fixed #253, which was that when a client indeed passes in a boolean `arriveBy`, `true`, when that gets passed in as a request to the backend, the type of `arriveBy` is now tragically a String, `'true'`. The unfortunate disaster is we only check for `'1'` or `true`, but not `'true'`.
Tested on dev server and ensured that we do return routes that have an ending time before the `arriveBy` time.
Here is the GET request I used: https://transit-testflight.cornellappdev.com/api/v1/route?arriveBy=true&end=42.4426153,-76.50927779999999&start=42.4439852,-76.48287359999999&time=1568948285&destinationName=Dufield%20Hall&originName=Statler%20Hall
Notice the arriveBy is true and the time is 1568948285, which is 
I suspect that iOS isn't actually passing in the true parameter, because I'm not sure why I …

Return routes that end at a time before the arriveBy time

---

src/routers/v2/RouteRouter.js

Updates the `arriveBy` bug for v2. 
We need to change the request parameter `isArriveBy` to `arriveBy` because iOS did not read the swagger docs. Because this is urgent, this PR won't deal with updating the docs -- just updating parameters so we can get the `arriveBy` working ASAP

Return v2/routes that have an end time before arriveBy time

---

src/API.js
src/routers/index.js
src/routers/v1/ApplePlacesRouter.js
src/routers/v1/AppleSearchRouter.js
src/routers/v1/SearchRouter.js
src/utils/SearchUtils.js

To convert from using GooglePlaces API to using Apple's FREE MapKit, here is my current plan:
When a user makes a search on iOS for a query, i.e. `Duff`, client will hit `/appleSearch` which will return an array of `busStops` AND an array of `applePlaces` if those places exist in our cache. If it doesn't, we just return an array of `busStops`. On client-side, when we see that server did not return any `applePlaces`, we will do the lookup for ApplePlaces and then send that array of `applePlaces` to `/applePlaces` which will just store these places in the cache. Now, the next time a user types in `Duff`, server will just return both the `busStops` and `applePlaces` and client will not need to do the lookup for ApplePlaces.
This PR accomplishes this plan by creating an `AppleSearchRouter` …

Add ApplePlaces & AppleSearchRouter

---

docker-compose.yml
src/utils/ParseRouteUtils.js

#264 Right now, we don't always return `delay` or `stayOnBusForTransfer` in our `directions` list that's returned by `v2\route`, which causes issues for iOS and is the reason for why the app shows a `could not fetch routes` error for only certain stops:
Thanks to @kevinchan159, I found that `mergeDirections` in `parseRouteUtils.js` was missing some fields (`delay` and `stayOnBusForTransfer`!) when it was merging routes, so I added the fields in with logic that:
1.  the combined delay is only the first bus route's delay, because that's how much the combined route is initially delayed by and is what the user needs to know in order to board the route on time
2. the combined `stayOnBusForTransfer` is only true if both routes' `stayOnBusForTransfer`s are true -- if you have to get off the bus …

Add delay and stayOnBusForTransfer fields for complete v2/route responses

---

README.md

Update README to better explain how to run locally, using additional information provided by @alanna-zhou .
Addresses the [issue raised here](https://github.com/cuappdev/ithaca-transit-backend/issues/259)

Update README to better explain how to run locally

---

src/API.js
src/routers/index.js
src/routers/v2/DelaysRouter.js

#262 
Right now iOS has to make a request for each route's delay, so now a DelaysRouter exists such that it can take in multiple tripID and stopIDs to get multiple delays:

Add new /delays endpoint for easier iOS handling of live tracking

---

src/routers/v1/MultiRouteRouter.js
src/routers/v1/PlacesAutocompleteRouter.js
src/routers/v1/SearchRouter.js
src/utils/AllStopUtils.js
src/utils/AnalyticsUtils.js
src/utils/Constants.js
src/utils/GraphhopperUtils.js
src/utils/TokenUtils.js

Centralized all the constants in one file, and removed the postman token because it was useless.
Again, sorry for the duplicate PR--for some reason, using the RETRY_COUNT constant in RequestUtils.js broke everything. Will be deleting the original PR once this gets merged in.
Currently testing on dev server (transit-dev:alanna) because it sometimes works and sometimes doesn't work

Clean up constants

---

src/swagger.json

The backend API documentation on swagger.io is currently outdated - some of the field names are inaccurate. I updated those fields in this documentation to reflect the actual API - see issue #267  
Additionally, I added a "schema" field to the requests to reference the schemas (which were already in the document), so the relevant schema appears in the request description. I also rephrased a few summaries and descriptions to aid in consistency and clarity. 
You can see what the new docs would look like by pasting the new swagger.json into https://editor.swagger.io (let the page convert the json into YAML).
The json is written using [Swagger 2.0](https://swagger.io/docs/specification/2-0/basic-structure/) conventions

Update swagger docs

---

docker-compose.yml

Master does not run locally due to Manish's changes. So, I am reverting it (in my other PR #273) and also updating our image tags so that it can be run!
Update image tags in docker-compose.yml so that when you run locally you can get the up-to-date routes (have the current GTFS data).
Manish will put in a new PR to fix his change!

Update image tags in local docker-compose.yml

---

src/utils/ParseRouteUtils.js
src/utils/RouteUtils.js

Right now, there are two cases in which we display a walking route (note that we always show a walking route), and here are screenshots of this tragic issue we've been having with walking times:
Here you can notice that the start time should actually be 11:56!
Once again, the start time should actually be 11:56!
There are a lot of entry points that I found that I could modify the bus routes. The way that I found that was most intuitive was in `ParseRouteUtils`. In `RouteUtils`, we first fetch routes with `GraphhopperUtils`, and then we parse them with `parseRoute` in `parseRouteUtils`. I thought that I should leave fetching to `GraphhopperUtils` and modifying the routes in `parseRouteUtils` since we have similar logic in there. What I did was check if the `route.transfers` attribute was …

Readjust walking route departure and arrival time due to bus buffer time

---

src/utils/GraphhopperUtils.js
src/utils/ParseRouteUtils.js

So right now, my walking route time fix is extremely flakey because there's this promise cycle detection error, and I finally figured out what the issue is. And it's because I've been directly modifying the `directions` array that's a promise!
So instead of directly modifying the `directions`'s first element's `startTime` and `endTime`, I created a new directions and appended the rest of the existing information so that I don't mess with all of this asynchronous jazz.
I've also renamed the return types to `Promise`s because this should be fixed eventually.
Currently deployed on dev and doesn't break anything. I'll let it sit for a while and then merge this PR in. 
I think I will write a Python script that checks for a valid `ithaca-transit-backend` JSON response -- because I think that …

Fix "promise chaining cycle" due to modifying promises in walking route

---

src/routers/v1/MultiRouteRouter.js
src/routers/v1/PlacesAutocompleteRouter.js
src/routers/v1/SearchRouter.js
src/utils/AllStopUtils.js
src/utils/AnalyticsUtils.js
src/utils/Constants.js
src/utils/GraphhopperUtils.js
src/utils/TokenUtils.js

Reverts cuappdev/ithaca-transit-backend#255
This commit currently results in a promise cycle error, and I verified this by deploying an image with this commit and it failed versus an image with the commit before. 
Will be investigating further on how to actually fix this PR, but for now I am reverting it so that I can get my walking PR reflected in transit prod!

Revert "Clean up constants" which has promise cycle error

---

docker-compose.yml
src/routers/v1/SearchRouter.js

We're still incurring some costs from Google Places API (very minor but still non-zero). This is probably because not everyone has updated the iOS app to the newest version which hits the AppleSearchRouter  which means that some users are still hitting the old v1 Search Router which currently has its own separate cache. (Thanks @kevinchan159 for the easy explanation to copy)
This change converts our v1 SearchRouter to use the same cache as the one in the AppleSearchRouter and it’ll help us cut some costs because a majority of our users are hitting the AppleSearchRouter anyway since they have updated. Also updated the `docker-compose.yml` to help things run locally as of the GTFS data now.
Tested this locally and it works. Will let this sit on the dev server for a bit before merging to …

Modify v1/search to use the same cache as v2/search

---

docker-compose.yml
src/utils/ParseRouteUtils.js

Right now, we show routes that are some 20-30 minutes before the departure time, be it arrive by or not.
I still need to investigate why this is happening, but for now I've put in a trivial fix so that our app doesn't look weird.
Trash the bus route if it's before the time that the user expects the leave when we parse bus routes.
Tested locally and on the dev server under `transit-dev:alanna`.
Will actually investigate what's going on and fix the early routes. 
Also, an issue with this change is that if there's some walking time before the bus route, it may still be earlier than the departure time. 
#284

Remove bus routes with an earlier start time than departure time

---

src/utils/ParseRouteUtils.js

Earlier I had made a PR trying to get rid of early bus routes, but that was just a temp fix. Did some digging today and found out that delayMs was NaN!
So the issue is that `direction.delay` is only checked if it is not `null`, but it could be `NaN`. Found this out thanks to [a very helpful Stack Overflow post](https://stackoverflow.com/questions/5515310/is-there-a-standard-function-to-check-for-null-undefined-or-blank-variables-in) about null values in JavaScript:
```
if( value ) {
}
```
will evaluate to true if value is not:
```
null
undefined
NaN
empty string ("")
0
false
```
So, all I did was check if `direction.delay` was true or not.
Works locally and also works deployed as `transit-dev:alanna` on the dev server as of right now.
We are done with this finally!
#285 
#284

Fix delay NaN handling that leaves early routes going undetected

---

src/swagger.json

Spent a full week on these docs. Accepting roasts
Fixed strings where we had "/" show up in the example response bodies, which can confuse people. Also looks like swagger added the "double" data type, so got rid of all of our "integer" and format "double". Also fixed all of the orderings of the responses, since it'll be easier for iOS and Android devs to debug if our responses match our docs.
A major change was the v2/appleSearch --  we were referencing our old googlePlace types.

Fix swagger docs' number types, data ordering, and response body examples

---

docker-compose.yml
src/routers/v1/TrackingRouter.js
src/utils/RealtimeFeedUtils.js

Again, sorry if I added too many reviewers, everyone goes MIA on me so I wanted to spam as many people as possible. Please help me get this approved ASAP so Android can ship within this semester!!
Currently, `/tracking` is an endpoint for `ithaca-transit-backend`, and right now it isn't returning data for the buses, and so the iOS and Android clients can't draw the buses on the map. This is the second step in my refactoring plan for addressing this issue:
1. Microservice parses protobuf for vehicle information from the TCAT third-party endpoint on vehicle positions
2. `/tracking` on ithaca-transit-backend needs to be modified so that it uses the newly merged ithaca-transit-microservice's `/vehicles` which takes in a `tripID` and `routeID` and returns important info like `longitude` and …

Refactor `/tracking` to make requests to the microservice and return valid vehicle info

---

src/swagger.json

Docs needed to be updated!
Updated the expected post request and response bodies for `/tracking` due to my latest PRs.
I forgot to update `/delays` and both Android and iOS agree that `/delay` can be deprecated so I just replaced that with the latest `/delays`.
#292

Update Swagger to reflect current `/tracking` and `/delays` 

---

docker-compose.yml
src/swagger.json
src/utils/RealtimeFeedUtils.js

Right now `/tracking` requires `routeID` and returns `routeID` but the Android team helped me realize that our backend views the `routeID` in the GTFS data (string in the GTFS) but returns it as a `routeNumber` (type Number). So I needed to make that change so that backend is consistent. I didn't choose to modify this in the microservice, because the whole point of the python code is to abstract that away from having to deal with what the clients know about our backend. 
Changed references of `routeID` to `routeNumber` and changed data type of string to number.
Updated docker compose to run locally.
Updated swagger docs to reflect new required field in request body and new field in response body.
Works locally, will be pushing onto servers soon.
#293 updated

Update `routeID` to be `routeNumber` in `\tracking` for consistency

---

docker-compose/ghopper/Dockerfile

Thanks to the legendary @meganle the Graphhopper Dockerfile has now been updated! TCAT updated the GTFS data and I had to rebuild a new Graphhopper Docker image but there was an issue with the `0.11-SNAPSHOT` jar file at `docker build`. With trial and error and dank googling skills, Megan was able to finesse this hella random fix (apparently master was broken at some point and the Graphhopper ppl fixed it). All credit cedes to her!!
Deleted the branch flags when cloning the Graphhopper repo and updated the Docker CMDs, particularly the jar file at runtime (when the Docker image is executed as a container).
Currently sitting on our ghopper server. Our live tracking had been crashing due to old trip ids, so this should be the fix. We have no choice otherwise--any other issue is most …

Update Graphhopper Dockerfile to be buildable

---

docker-compose/ghopper/Dockerfile

We were getting this error on the server:
The first line (gotta scroll) is the most relevant!
``` 
2020-05-09 23:04:07.060 [dw-14 - GET /route?ch.disable=true&pt.arrive_by=false&pt.earliest_departure_time=2020-05-09T22%3A23%3A59.474Z&pt.max_walk_distance_per_leg=2000&pt.profile=true&pt.walk_speed=3&elevation=false&point=42.444971674516864%2C-76.48098092526197&point=42.45088471606147%2C-76.49364531040192&points_encoded=false&vehicle=pt&weighting=short_fastest] INFO  c.g.h.IllegalArgumentExceptionMapper - bad request: Vehicle not supported: `pt`. Supported are: `car`
You should consider using the `profile` parameter instead of specifying a vehicle.
Available profiles: [car]
To learn more about profiles, see: docs/core/profiles.md
```
Basically `pt` is public transport, but the version on …

Fix Graphhopper vehicle `pt` not supported

---

docker-compose.yml
docker-compose/ghopper/Dockerfile
src/utils/ParseRouteUtils.js

The date time we get from TCAT has changed format sometime over the summer. They now include milliseconds unfortunately. We need to revert this format back to what it was so that clients don't break.
Date format we had before that we should maintain: `yyyy-MM-dd'T'HH:mm:ssZZZZ`
Date format that TCAT changed to over the summer: `yyyy-MM-dd'T'HH:mm:ss.SSSZ`
* Stripped milliseconds off dates from TCAT if they exist
* Updated `docker-compose.yml` so we can run things locally with this change
* Updated the `ghopper` `Dockerfile` because Tom sent me data manually (can't fetch from the URL) so to keep versions matching with docker images, we should have master keep this change--once we can start fetching again (Aug 30), I'll update master
* Currently deployed on prod and dev from my branch and …

Strip date of milliseconds to fix 4:07 error

---

.github/CONTRIBUTING.md
.github/pull_request_template.md

This is super meta but I getting really annoyed always having to delete the intro on how to make a good PR title. I think everyone here already knows how to do this...
Basically everytime I delete it, Github detects the markdown as the start of an issue:
* Remove redundant descriptions (like who doesn't understand this stuff after reading the titles??)
* Add an HTML tag template for adding images so that we can resize and that is *actually* useful instead of having to click on a dropdown and seeing some image swallow up your whole screen

Update PR template

---

docker-compose.yml
docker-compose/ghopper/Dockerfile
src/utils/RealtimeFeedUtils.js

Last semester, Android requested that I change the POST request field `routeID:string` to be `routeNumber:integer` because that was consistent with `v2/route`. However, this won't work with old iOS clients, who send in `routeID:string` and expect `routeID:integer` as a response. Don't ask me why this isn't consistent, but it looks like Android will just have to deal with this. So, whatever we return `routeNumber:integer` in `v2/route`, just change the name to `routeID` and cast it to a string before putting into `v2/tracking`. Make sure you expect the response to be `routeID:integer` as well.
Thanks to @Omarrasheed, I've updated the response to include everything that the iOS clients need:
Update /tracking so that old iOS clients still work
Update docker images so we can run locally …

Ensure /tracking is backwards compatible

---

src/swagger.json

Pretty important change because we have newbies on iOS and Android now -- I'm surprised I didn't catch this earlier :'(
Just add a trivial "v2" in front of two endpoints and update /tracking [since I last made it backwards compatible](https://github.com/cuappdev/ithaca-transit-backend/pull/305) and decided to not use `routeNumber` so that we could make a v3 route that was better (we call GTFS's `routeID` a `routeNumber` which is pretty jank...)
Just docs 
Nothing, this is just docs
#267

Update docs to have v2 at /tracking and /delays

---

src/API.js
src/routers/index.js
src/routers/v3/RouteRouter.js

Some really redundant/jank things we want to get rid of from v2:
* routeSummary
* delays
* routeID -- no longer using for analytics!
* routeNumber -- since we delete routeID, we can change this to routeID
* Copy v2 into a v3 route
Works locally, and although it's a minor change I'll be deploying to the server
* Might want to consider refactoring delays to return the delays for a specific stop
#307

Begin v3/route by copying v2 into a new v3

---

src/routers/v3/RouteRouter.js
src/utils/ParseRouteUtilsV3.js
src/utils/RouteUtilsV3.js

For a v3, iOS let me know that they don't need `Route Summary` anymore, and Android kindly is (in the process of?) pivoting to deprecating `Route Summary`! The point of this PR is to make v3 super clean and significantly less bulkier than v1 and v2. This may seem contradictory rn because I have to add extra files, but it's the only way I can make changes so that we can still offer backwards compat. Maybe a couple years down the line the next backend member can refactor these files into v1, but for now we're just going to have to deal with multiple versions of utils files :')
Add `ParseRouteUtilsV3` and a `RouteUtilsV3` so that we can remove `Route Summary` as a field for a route in `v3/route`.
Tested locally and it successfully removes route summary :)
I'll deploy this onto the devserver …

Add v3 utils files in order to remove Route Summary

---

docker-compose.yml
src/API.js
src/routers/index.js
src/routers/v2/DelayRouter.js

iOS uses a `v2/delay` route instead of `v2/delays` - for the sake of backwards compatibility with people who don't update, I added a delay route. 
Added a new `DelayRouter` with similar functionality as `DelaysRouter`, but it only accepts a single trip, and accepts it via the query parameters instead of the request body (as in `v1`).  
Some manual testing, and ran integration locally.

Add Delay Route for Backwards Compatibility with iOS

---

docker-compose/ghopper/Dockerfile

Ghopper GTFS wget URL was using old S3 path conventions that are planned to be deprecated. 
Updated URL to modern style.
Built Dockerfile and it worked.

update ghopper wget url to modern aws path name

---

src/index.js
src/utils/NotificationUtils.js

Initially, `rtfData` was only being declared and never initialized, causing no notifications to be sent at all, even though the endpoint works.

Get RTF Data from source in Notification Loop
