src/Raptor.js
src/TCAT.js
src/models/Kml.js
src/models/Location.js
src/routes/BusRouting.js
src/utils/KmlUtils.js

I've added a model that takes in a placemark KML string and does the proper parsing. I thought it would be better to integrate it into the model's constructor for ease of use, but the code can be easily factored out in case that is not preferred.

KML Integration

---

src/routers/GetRouteRouter.js

one line addition of a secondary sort based on Path ```startTime```
@shivvo 
@mattbarker016

secondary sort

---

env.template
src/routers/RouteRouter.js
src/server.js
src/utils/RouteUtils.js
src/utils/TCATUtils.js

Prepares the code to be deployed via swarm, and moves the references to other containers to environment variables

Swarm-ready deployment

---

scripts/setup.sh

Fixed setup script to make sure graphhopper is on version `0.10`

fixed Issue #47: setup script

---

.travis.yml
package-lock.json
package.json

* TravisCI setup done
* `jest` package updated
* `package-lock.json` updated accordingly

TravisCI Integration

---

src/routers/AlertsRouter.js
src/routers/AllStopsRouter.js
src/routers/DelayRouter.js
src/routers/HelloWorldRouter.js

Would appreciate any suggestions (content, amount of documentation) on the docs for simple routers before I start working on the messier ones!
#85 #86

Add basic documentation for routers

---

.hound.yml

Reverts cuappdev/ithaca-transit-backend#106

Revert "Delete hound"

---

src/utils/GTFSUtils.js
src/utils/ParseRouteUtils.js
src/utils/ParseRouteUtilsV2.js
src/utils/RequestUtils.js
webpack.config.js

Changed line lengths to 120, decouple testing from dev testing

---

src/utils/AlertsUtils.js
src/utils/RequestUtils.js

Verified nothing broke:
Verifying nothing uses the `start` export:

Improve naming in AlertsUtils

---

src/utils/EnvUtils.js
src/utils/GraphhopperUtils.js
src/utils/LogUtils.js
src/utils/ParseRouteUtils.js
src/utils/ParseRouteUtilsV2.js
src/utils/RealtimeFeedUtils.js
src/utils/RequestUtils.js
src/utils/TokenUtils.js

Add EnvUtils.js to centralize process.env calls

---

src/server.js
src/test/Unit.test.js
src/utils/GraphhopperUtils.js

Everything is working, about to go to sleep 💤 – will check this tomorrow morning!
Verifying that all instances of `ghopperReady` were changed:

Begin refactor of GraphhopperUtils

---

src/appdev/ApplicationAPI.js
src/server.js
src/test/TestUtils.js
src/utils/LogUtils.js
src/utils/RealtimeFeedUtils.js
src/utils/RequestUtils.js

Removed `// eslint-disable-next-line no-console` because I allowed it in `.eslintrc`. I also refactored some other code, no functionality was changed.

Remove eslint-no-console, minor misc refactoring

---

src/utils/AlertsUtils.js
src/utils/AllStopUtils.js
src/utils/RealtimeFeedUtils.js
src/utils/RequestUtils.js
src/utils/TokenUtils.js

Verified nothing broke:
Verifying that I replaced all instances of renamed functions:

Refactor RequestUtils.js

---

src/routers/AlertsRouter.js
src/routers/DelayRouter.js
src/routers/MultiRouteRouter.js
src/routers/PlacesAutocompleteRouter.js
src/routers/RouteRouter.js
src/routers/RouteSelectedRouter.js
src/routers/TrackingRouter.js
src/utils/RealtimeFeedUtils.js

I have a suspicion some routers aren't being called at all, I'd like to kill the ones that aren't being used once we have a little more data.

Add logging to RealtimeFeedUtils and all routers

---

src/server.js
src/utils/RealtimeFeedUtils.js

Incorporates changes from https://github.com/cuappdev/ithaca-transit-backend/pull/137 as well

Fix RTF bug related to new microservice

---

src/utils/RealtimeFeedUtils.js

Fix red banner constantly displaying

---

docker-compose/docker-compose.yml
env.template
src/appdev/ApplicationRouter.js
src/routers/AlertsRouter.js
src/routers/DelayRouter.js
src/routers/MultiRouteRouter.js
src/routers/PlacesAutocompleteRouter.js
src/routers/RouteRouter.js
src/routers/RouteSelectedRouter.js
src/routers/TrackingRouter.js
src/utils/EnvUtils.js
src/utils/RealtimeFeedUtils.js

- Removed some logging to avoid RTF overload
- Moved logging for routers into `ApplicationRouter`
- Updated `docker-compose.yml` with the tcat microservice

Minor logging changes

---

src/routers/MultiRouteRouter.js
src/routers/RouteRouter.js
src/server.js
src/utils/RouteUtils.js

More fixes:
- Some progress for #102, walking routes are always appended
- Fixed bug where walking route would have a start time of 5 minutes earlier than the search
- Decreased delay for startup of server if `RTF` is not running
- Refactored code in `RouteUtils`

Always add walking routes at the bottom of results

---

.dockerignore
README.md
src/appdev/ApplicationRouter.js
src/routers/AlertsRouter.js
src/routers/AllStopsRouter.js
src/routers/DelayRouter.js
src/routers/HelloWorldRouter.js
src/routers/MultiRouteRouter.js
src/routers/PlacesAutocompleteRouter.js
src/routers/RouteRouter.js
src/routers/RouteSelectedRouter.js
src/routers/TrackingRouter.js
src/utils/RouteUtils.js

Issue #151, #153 
- Changed `ApplicationRouter` to support multiple request types
- Fix up `MultiRouteRouter` and updated README with updated spec.
- Changed `RouteRouter` to support `POST`
cc @ywsang

Fix RouteRouter & MultiRouteRouter

---

src/utils/ParseRouteUtils.js
src/utils/RouteUtils.js

Issue #149 
- Ensure that routes always have a minimum one minute difference
Verified on dev server
Screenshots:

Add 1 minute time difference check

---

.dockerignore

Remove tcat-ny-us from .dockerignore

---

src/utils/GTFSUtils.js
src/utils/ParseRouteUtils.js

Issue #157 
Works on dev server

Delete getting routes from GTFSUtils

---

src/API.js
src/routers/HelloWorldRouter.js
src/server.js
src/test/Main.test.js
src/utils/ParseRouteUtils.js
src/utils/RequestUtils.js
src/utils/RouteUtils.js
src/utils/TokenUtils.js
webpack.config.js

Tried to simplify logic wherever possible, checked `logs.cornellappdev.com` to see if there were any Error cases that weren't being reached, verified that everything works on devserver.

Clean up code, remove unnecessary checks

---

docker-compose/map/Dockerfile

First of a few PRs to tackle #178, I verified that this new image works. I updated the Graphhopper minor version, and decreased the image size by moving to an `alpine` based image.

Refactor Graphhopper Map

---

README.md

Update README for /allStops

---

src/routers/v1/SearchRouter.js
src/utils/RouteUtils.js

Closer to finishing #195!
This file is also flow-error free now, and I ended up removing 55 LOC :)

Refactor RouteUtils further

---

src/appdev/ApplicationRouter.js
src/appdev/ApplicationUtils.js

Add epoch and formatted EST time to logging requests

Add epoch and formatted time to logs

---

src/utils/ParseRouteUtils.js
src/utils/RouteUtils.js

Fix walking isArriveBy time from start time to end time

---

package-lock.json
package.json
src/API.js
src/appdev/ApplicationAPI.js
src/appdev/ApplicationRouter.js
src/routers/DocsRouter.js
src/routers/index.js
src/swagger.json

Swagger Docs

---

src/utils/GraphhopperUtils.js
src/utils/RouteUtils.js

Addresses #201 
- Change delayBufferMinutes to be a constant of 1 minute so that we show bus routes that depart at the same minute

Change delayBuffer to a constant

---

src/utils/GraphhopperUtils.js
src/utils/RouteUtils.js

Addresses #201 without any side effects

Display recent routes

---

src/test/Unit.test.js
src/utils/GraphhopperUtils.js
src/utils/ParseRouteUtils.js

Make 2 Ghopper requests to display delayed routes

---

src/routers/v1/RouteRouter.js
src/utils/RouteUtils.js

Addresses #144 
I added a `containsTransfer` field to the LogUtils in `RouteRouter` which will tell us if the current route request returned a route w/ a transfer.

Log requests that contain a route with transfer

---

src/utils/GraphhopperUtils.js

Addresses #222 
This PR adds an additional Graphhopper bus request with a delay buffer of 40 mins. This is to account for the time it takes for people to walk from their Current Location to the bus stop for bus routes in the past 20 mins w/ delay

Add second delay buffer request

---

src/swagger.json

Love me some good documentation
Fix type on `minutesBefore` field in swagger
We don't test here
Become true full stack developer

Fix type on minutesBefore field

---

src/swagger.json

Reverts cuappdev/ithaca-transit-backend#279
This is so that I can revert the notifications PR #278 because it doesn't seem to work. Will be adding this back once I figure it out more.

Revert "Fix type on minutesBefore field"

---

src/swagger.json

Our docs are missing better examples for the android team to go off on.
Made more descriptive examples for our v2/route request bodies.
It's just docs man. Works locally tho!
Will try to improve docs as I come across janky things.
#267

Add better route descriptions for swagger docs

---

package-lock.json
package.json
src/controllers/RouteReportingController.js
src/index.js
src/swagger.json
src/utils/ParseRouteUtilsV3.js
src/utils/RouteReportingUtils.js

Create an endpoint to retrieve the closest bus on a route to a given location.
I created `RouteReportingController.js` and `RouteReportingUtils.js` to handle fetching the closest vehicle given a route. To use the `DistanceBetweenPointsMiles` function from `ParseRouteUtilsV3.js`, the file was modified to export that function. I also added the endpoint to `index.js`.
Manually tested the endpoint by using the route to fetch the closest bus from different starting locations and comparing it to the bus actually closest to a given location.
Update the route to take into return the closest bus in the same direction as the user's trip direction.

Route Reporting/Retrieving Closest Bus

---

src/swagger.json

Indicate when fields are possibly null for frontend decoding errors. Also updated the models to be compatible with OpenAPI 3.0.

indicate nullable field on swagger doc

---

src/controllers/NotificationController.js

Dependency for frontend (error/success/data handling is abstracted and requires the same format throughout the controllers.

Update Notification response to be consistent with rest of codebase
